stages:
  LOADING_DATA:
    cmd: python3 -m src.init.load_data
    deps:
    - src/DATA/raw/dpe-france.xlsx
    - src/init/paths.py
  PREPROCESSING:
    cmd: python3 -m src.processing.preprocess
    deps:
    - params.yml
    - src/DATA/raw/dpe-france.xlsx
    - src/init/config.py
    - src/init/paths.py
    outs:
    - src/DATA/processed/df_prepare.xlsx
  FEATURE_ENGINEERING:
    cmd: python3 -m src.processing.feature
    deps:
    - params.yml
    - src/DATA/processed/df_prepare.xlsx
  TRAIN:
    cmd: python3 -m src.processing.train
    deps:
    - params.yml
    - src/DATA/processed/df_prepare.xlsx
    - src/init/load_data.py
    - src/processing/feature.py
    outs:
    - src/DPE_MODELS/X_test.csv
    - src/DPE_MODELS/pde_model.pkl
    - src/DPE_MODELS/y_test.csv
