stages:
  PRETRAITEMENT:
    cmd: python3 ./DVC-GithuActions-Proj/src/Processing/preprocess.py
    deps:
    - ./DVC-GithuActions-Proj/DATA/raw/dpe-france.xlsx
    - ./DVC-GithuActions-Proj/src/init/load_data.py
    - ./DVC-GithuActions-Proj/src/init/paths.py
    outs:
    - ./DVC-GithuActions-Proj/DATA/processed/df_prepare