# params.yml the file who contains all parameters for the project

preprocess:
  imputation_method: median

feature_engineering:
  target: consommation_energie

split:
  test_size: 0.2
  random_state: 20000
  shuffle: True

models:
  linear_regression:
    fit_intercept: True
    normalize: True
    n_jobs: -1

  random_forest_regressor:
    random_state: [20000, 30000, 42]
    n_estimators: [200, 300, 500]
    max_depth: [100, 150, 200]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    n_jobs: -1

  gradient_boosting_regressor:
    random_state: [20000, 30000, 42]
    n_estimators: [100, 200, 300]
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [1,3, 5, 7]
    loss: ['squared_error','absolute_error']
    min_samples_split: [2, 5, 10]
  
  elastic_net:
    random_state: [20000, 30000, 42]
    alpha: [0.1, 1.0, 10.0]
    l1_ratio: [0.1, 0.5, 0.9]
    max_iter: [1000, 2000, 5000]

  voting_regressor:
    estimators: 
      - random_forest_regressor
      - gradient_boosting_regressor
      - elastic_net
    voting: 'hard'
    n_jobs: -1
evaluation:
  metrics:
    - r2_score
    - mean_absolute_error
    - mean_squared_error
    - root_mean_squared_error
