stages:
  PRETRAITEMENT:
    cmd: python3 -m src.processing.preprocess
    deps:
    - DATA/raw/dpe-france.xlsx
    - src/init/load_data.py
    - src/init/paths.py
    - src/processing/preprocess.py
    outs:
    - DATA/processed/df_prepare.xlsx
  FEATURE:
    cmd: ENGINEERING -d src/processing/feature.py -d 
      DATA/processed/df_prepare.xlsx python3 -m src.processing.feature
  TRAIN:
    cmd: python3 -m src/processing/train.py DPE_MODELS/pde_model.pkl
    deps:
    - DATA/processed/df_prepare.xlsx
    - params.json
    - src/processing/feature.py
    - src/processing/train.py
    outs:
    - DPE_MODELS/X_test.csv
    - DPE_MODELS/pde_models.pkl:
        cache: false
    - DPE_MODELS/y_test.csv
  EVALUATION:
    cmd: python3 -m src/processing/evaluate.py
    deps:
    - DATA/processed/df_prepare.xlsx
    - DPE_MODELS/X_test.csv
    - DPE_MODELS/pde_models.pkl
    - DPE_MODELS/y_test.csv
    - params.json
    - src/processing/evaluate.py
    - src/processing/feature.py
    - src/processing/train.py
    outs:
    - DPE_MODELS/metrics.json
  FEATURE_ENGINEERING:
    cmd: python3 -m src.processing.feature
    deps:
    - DATA/processed/df_prepare.xlsx
    - src/processing/feature.py
